update

diff --git a/bin/list_pin b/bin/list_pin
--- a/bin/list_pin
+++ b/bin/list_pin
@@ -23,46 +23,93 @@
 # ==============================================================================
 # GLOBAL VARIABLES
 # ==============================================================================
+PROGNAME=$(basename "${BASH_SOURCE}")
+PROGDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+locID=${2:-R*C*}
+
+usage() {
+    cat <<- EOF
+
+          USAGE: $PROGNAME [OPTIONS] [WaferID] [PinID]
+
+    DESCRIPTION: This utility compiles the binning data generated by the pin
+                 probe testers. If the necessary SMB shares are not currently
+                 mounted, this utility will also mount shares and search in the
+                 correct directory using the calient_mount library. Currently
+                 under development and only portable for Mac OS X operating
+                 systems with up to date non-framework GNU Bash 4+ shells.
+                 Further development will allow for portability to Linux and
+                 POSIX compliant shells is in progress. This is a release
+                 candidate script and is not meant to be used in production
+                 level enviornments.
+        OPTIONS: [-h help] [-t test]
+   REQUIREMENTS: Library: calient_mount.sh
+                 Library: testing.sh
+                 GNU Bash 4+
+         AUTHOR: Sang Han
+   ORGANIZATION: Calient Technologies
+       REVISION: 2.0.0rc
+
+	EOF
+}
 
 parse_pin() {
     local pin_data="$1"
-    local pin_grep=$(\
-        tr -d '\n' <<- EOF
-    '
-    %Mirror ID:|
-    %Operaror:|
-    %Comment:|
-    %Start Date|
-    101 - Shorted|
-    102 - Over Current|
-    103 - No Deflection|
-    105 - Off Azimuth|
-    104 - Bad Initial Angle|
-    106 - V Limit Poor Deflect|
-    107 - M Limit Poor Deflect|
-    108 - V Limit Full Deflect|
-    109 - M Limit Full Deflect|
-    100 - Full Deflection
-    '
-EOF
-    )
-    {
-        head "$pin_data";
-        tail "$pin_data";
-    } | \
-        grep -E "$pin_grep"
+    printf "%sMirror ID:,%s\n" "%" "$file_name"
+    head -n 6 "$pin_data" | tail -n 4
+    tail "$pin_data"
+}
+
+cleanup() {
+    return
 }
 
 main() {
-    declare -a pin_logs
+    if [ -f "/tmp/pin_log.csv" ]; then
+        rm "/tmp/pin_log.csv"
+    fi
+    declare -a file_names
     for file in * ; do
         if [[ -f $file ]] && [[ $file =~ .csv$ ]]; then
-            pin_logs+=("${file%%.csv}")
-            echo ${pin_logs[-1]}
-            parse_pin "$file"
+            file_names+=("${file%%.csv}")
+            file_name=${file_names[-1]}
+            awk '
+                BEGIN {
+                    FS=","
+                    OFS=","
+                }
+                {
+                    if ($2 == "") {
+                        $2 = 0
+                    };
+                    print $1, $2
+                }
+                END {
+                    printf "\n"
+                }' <(parse_pin "$file")
         fi
     done
+    printf "Found %s files\n" "${#file_names[@]}"
 }
+
+# ===============================================================================
+# Parse Options
+# ===============================================================================
+declare -i TEST=0
+while getopts ":ht" options; do
+    case ${options} in
+        h) usage
+           exit 0
+            ;;
+        t) TEST=1
+           ;;
+        \?)
+            echo "Invalid options: -${OPTARG}" >&2
+            exit 1
+            ;;
+    esac
+done
+    shift $((OPTIND-1))
 
 if [[ "$0" == "${BASH_SOURCE[@]}" ]]; then
     main
